### ISSUE TITLE
User can record

### ISSUE THREAD

**Issue by mchype99** [ios-Group12/sorting-synthesizer#10]
- [x] Create record button on Synth screen
- [x] Create stop button on Synth screen
- [x] Recording starts when record button is tapped
- [x] Recording stops and is saved when stop button is pressed
   - [x] Recording is uploaded to Parse server

**Comment by slightlydrifting** [comment]
This sprint will span multiple weeks due to its dependancies on other sprints being completed. Currently recordings can be uploaded to Parse server via recording button.
