### ISSUE TITLE
User can change octave

### ISSUE THREAD

**Issue by mchype99** [ios-Group12/sorting-synthesizer#8]
- [x] Create ability to include/exclude octave ranges

**Comment by slightlydrifting** [comment]
This will be implemented into "3" ranges the user can activate. Low-Mid-High frequency ranges. These need to be further tested before merging into master. The +/- range is too exclusive of a feature without having a musical keyboard.

**Comment by slightlydrifting** [comment]
Testing complete, this feature includes a low/med/high button that slices the array before it is shuffled and sorted.
