### ISSUE TITLE
User can change sorting algorithm

### ISSUE THREAD

**Issue by mchype99** [ios-Group12/sorting-synthesizer#9]
- [x] Create knob for choosing algorithm
 - [x] Create each sorting algorithm
 - [x] When an algorithm is tapped the algorithm is changed

**Comment by slightlydrifting** [comment]
I've added 4 sorting algorithms:
Insertion Sort; Merge Sort; Bubble Sort; Selection Sort
The user can change which algorithm is driving the oscillator by going to settings and tapping the rotary dial. Issue complete.
